services:
  mariadb:
    image: docker.io/mariadb:10.11.9
    platform: linux/amd64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3307:3306

  redis-cache:
    image: docker.io/redis:alpine
    platform: linux/amd64

  redis-queue:
    image: docker.io/redis:alpine
    platform: linux/amd64

  frappe:
    image: docker.io/frappe/bench:latest
    platform: linux/amd64
    command: sleep infinity
    # command: bash -c "cd bench-14 && bench start && cat"
    environment:
      - SHELL=/bin/bash
    volumes:
      - ../..:/workspace:cached
      # Enable if you require git cloning
      - ${HOME}/.ssh:/home/frappe/.ssh
    working_dir: /workspace/development
    ports:
      - 8004-8006:8000-8003
      - 9004-9006:9000-9003
    depends_on:
      - mariadb

volumes:
  mariadb-data:
  #postgresql-data:
  #mailpit-data:
